[project]
name = "news-app-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dynaconf>=3.2.12",
    "fastapi>=0.127.1",
    "uvicorn[standard]>=0.40.0",
]
